language: java
jdk:
  - oraclejdk8
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OPsuYEMd/QRtNcLU5S+Qwq876zc29pqgU3God+pLEkFwz03PxQ/pedc1/ppSMVFPKEb294p9PdfwybT/7+ULFkT5bMdE2Ed3HJoGN8vgffLQUoSFWNHO2bRYYsCQPknU67hLBCRK0P7Zy6gzAVrA3bw4kRXALi/jW0d2T6cF0F7HYi1AM++NoFflnntrGGVwjommuNOW7zuge6epPErx51My6hoOJ6zlUqr3UoknlWWXZ5j3QxxswCJQehSE26P8d7yhHjCSSdK8c0WM/DpN6r2oL4UCjgZNd3eMD/vq0djqSuwuu2bqfdQz+GEq12N6SHMobf7EVN2uk0RTKqzgUDdUVdm2T/Rd9zmlQvU+3OL+2xC4E/TCjsU5enFGZ5OpL+bBFeu2QHJCulVnURux8hY+/aHPa5Suogn0e7pGI6phAMuLZoUDj4GqN/GjxWW+3pHgiF7gDF2loPUXSdPlmVtdlQSYOyNyZINXzPx3eNAMEw+qhcjBBzW408HmacmwGgCj0h0PLyjHG5gnmJlRafQ0vig/Dc/uOrWtEx/676BXUNlRJ8kvLwY+pf8vJp3Vz3jmaUrLJmanptF19QdNpxedBx1SEQBNUIo7JuZ7UhYk5qUw5pmjDKqNzs0g6U1+K6GRSFCtO4Hig5d+PAOBy1kKUfeuoZEkXkfQ7xQIYYo=
  file: build/distributions/xld-kubernetes-plugin-6.2.6.xldp
  on:
    repo: xebialabs-community/xld-kubernetes-plugin
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: DAbJbJAw9Dxn8qubLkaBL4uzDs4+0g39k2zseDge6LxtowpnNGtf/iGa1s+iFe8ql5evqMuHq5PJHzKQ0n95G8WhuhcL6klPnX/SETz2xKREu6m7OAXqbJHdUdm5516QmDl+q4MMNiR93Ws4VlDGYxdjfb8l1BQipoJC4mwzDuDb/cKN1r6bywKTUOpBHNbRN7uo0pSo4profxUFMRfGdM9KGxu89TgPMvb5+AWcKZHEMgamivh+KSUut/KuQZPP9o2+0myHhmMzSLEmppCCWpOdI6kwDMwdRKNpv4m7duk+P5Ilgtm6B9VWGpgD0ad5+WKrBL+afWdDD4GLF631gKrk987Aj3O8nLwa9EpAq+LW8Fh6vMp1rAvSbDCvDFrE2rFq1mhoAbH1GJTlhd+Sjqfypo/fdyZwFBctrGbNZvbx5oCcolcMfI2cp//wtKMa9y9of3uwfinsqTnYVTdmTQkit8iPwMoR+Jba1Kij1rhMRk6TDIIOySXdXvbUT4MDyw96Ib+StqdXc1TukSFqoTaNeK/JPcmj0sTv0voJ5NeZl1HbvT6B57Ie874VNa8f110CyDf9svrvQ2ZOB7RFP88DGCDbGypAynVewY27/MBNaDMdohXAJcWXePQM5UD9bBfvYvE5qfD28N1LshI8omCBRWN6dr4OguVsAgkSxSg=
