language: java
jdk:
- oraclejdk8
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OPsuYEMd/QRtNcLU5S+Qwq876zc29pqgU3God+pLEkFwz03PxQ/pedc1/ppSMVFPKEb294p9PdfwybT/7+ULFkT5bMdE2Ed3HJoGN8vgffLQUoSFWNHO2bRYYsCQPknU67hLBCRK0P7Zy6gzAVrA3bw4kRXALi/jW0d2T6cF0F7HYi1AM++NoFflnntrGGVwjommuNOW7zuge6epPErx51My6hoOJ6zlUqr3UoknlWWXZ5j3QxxswCJQehSE26P8d7yhHjCSSdK8c0WM/DpN6r2oL4UCjgZNd3eMD/vq0djqSuwuu2bqfdQz+GEq12N6SHMobf7EVN2uk0RTKqzgUDdUVdm2T/Rd9zmlQvU+3OL+2xC4E/TCjsU5enFGZ5OpL+bBFeu2QHJCulVnURux8hY+/aHPa5Suogn0e7pGI6phAMuLZoUDj4GqN/GjxWW+3pHgiF7gDF2loPUXSdPlmVtdlQSYOyNyZINXzPx3eNAMEw+qhcjBBzW408HmacmwGgCj0h0PLyjHG5gnmJlRafQ0vig/Dc/uOrWtEx/676BXUNlRJ8kvLwY+pf8vJp3Vz3jmaUrLJmanptF19QdNpxedBx1SEQBNUIo7JuZ7UhYk5qUw5pmjDKqNzs0g6U1+K6GRSFCtO4Hig5d+PAOBy1kKUfeuoZEkXkfQ7xQIYYo=
  file: build/distributions/xld-kubernetes-plugin-6.2.6.xldp
  on:
    repo: xebialabs-community/xld-kubernetes-plugin
    all_branches: true
    tags: true
notifications:
  slack:
    secure: H0Xtd7p3VMMZVD1s4EBgGlQVRjB0kMgV0pth4+30BrOtPB4IfR04f7sgyyCejhEqx9YD+eDHcTYyufzXWgsNgTXqOCHGP441HBdmM58gcFpzds1ggETLi6mCR0pBBoLAM0WLNe9lDxIwycGm4iC4NFw6bMzYZaaTkX2VYdQ6FhOTktc8s20aWLD6uBII5l38NJsLIWS0DVpbAWA2pgwR/1QgqWtx2VemGI6cRMEsUS+7Hl/Bht5ngweADOo3KHkwaoCFwyR78alm6WYPrQa2WjUq545rrACZe2wstY0CX+EYAJomj8BsYQUBdm0YJjq30tKxzl+iXnQ16dX/AzItau0R9TiL9NQKPdxk7M/bCXJGoat+rAruo92UXgA2trt+H/Jwe7EL5tfGm0x9IJpgLM9Az1SHIkSW9iio4UezVOvyuO8etDFcqkok4uOyCNbUNn5/tURv4eHxDC5UYow2Pn/e2Xz/PcrK37J0wKcimepDurTApKNOnRrIeNMxNqHBmHoRfjedI95N/m/58bOcRbG5Yz6Y6/39tOfo6u7Aq2aodyxRI8XW/n9ejc/OJFcJ9JT8ebnOabQwm1LzNWNmge4e3OZIAVCxeDZmfa96EYyO+XPMw8Ye3CCJ9teysnvJ2y3hH7cxrXaoozZy+Q0232Yil6zrn2qUo2F2JgIdrvA=
